version: "3.8"

services:
  barcode-scanner-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barcode-scanner-web
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - SCANDIT_LICENSE_KEY=${SCANDIT_LICENSE_KEY}
    networks:
      - app-network

  # Optional reverse proxy if you need HTTPS
  # nginx-proxy:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/conf:/etc/nginx/conf.d
  #     - ./nginx/certbot/conf:/etc/letsencrypt
  #     - ./nginx/certbot/www:/var/www/certbot
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
